/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    BASE_PATH: process.env.BASE_PATH,
    BASE_API_URL: process.env.BASE_API_URL,
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
    FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
    API_INA_BASE_URL: process.env.API_INA_BASE_URL,
    ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
    ENCRYPTION_TYPE: process.env.ENCRYPTION_TYPE,
    SERVICE_APP_KEY: process.env.SERVICE_APP_KEY,
    SERVICE_ACCESS_KEY: process.env.SERVICE_ACCESS_KEY,
    DATADOG_APPLICATION_ID: process.env.DATADOG_APPLICATION_ID,
    DATADOG_CLIENT_TOKEN: process.env.DATADOG_CLIENT_TOKEN,
    DATADOG_SITE_NAME: process.env.DATADOG_SITE_NAME,
    DATADOG_SERVICE_NAME: process.env.DATADOG_SERVICE_NAME,
    DATADOG_DEFAULT_ENV: process.env.DATADOG_DEFAULT_ENV,
    DATADOG_PRIVACY_LEVEL: process.env.DATADOG_PRIVACY_LEVEL,
    DATADOG_SESSION_SAMPLE_RATE: process.env.DATADOG_SESSION_SAMPLE_RATE,
    DATADOG_REPLAY_SAMPLE_RATE: process.env.DATADOG_REPLAY_SAMPLE_RATE,
    DATADOG_FORWARD_ERRORS_TO_LOGS: process.env.DATADOG_FORWARD_ERRORS_TO_LOGS,
    GOOGLE_GENAI_APIKEY: process.env.GOOGLE_GENAI_APIKEY,
  },
  basePath: process.env.BASE_PATH,
  assetPrefix: process.env.BASE_PATH,
  compiler: {
    removeConsole: {
      exclude: ["error"],
    },
  },
};

export default nextConfig;
